FROM node:20.14.0 AS base

WORKDIR /src

COPY package*.json ./

RUN yarn install --frozen-lockfile

FROM base AS development

COPY . .

CMD ["yarn", "dev"]

FROM base AS production

COPY . .



CMD ["yarn", "dev"]

EXPOSE 7000
